spring:
  # Datasource cho non-sharding operations
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345678
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # Jackson config
  jackson:
    default-property-inclusion: non_null

  # Redis config
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  # Exclude ShardingSphere auto configuration vì chúng ta dùng manual config
  autoconfigure:
    exclude:
      - org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration

# Logging
logging:
  level:
    root: INFO
    org.apache.shardingsphere: INFO
    com.example.sharding: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Custom properties cho sharding (nếu cần)
sharding:
  tenant:
    default-size: 4
    algorithm-class: com.example.sharding.sharding.TenantSharding

