spring:
  jackson:
    default-property-inclusion: non_null

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  autoconfigure:
    exclude:
      - org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration

logging:
  level:
    root: INFO
    org.apache.shardingsphere: INFO
    com.example.sharding: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

sharding:
  tenant:
    default-size: 4
    algorithm-class: com.example.sharding.sharding.TenantSharding
  country:
    algorithm-class: com.example.sharding.sharding.CountrySharding
